public class Constants {
    public static final String FOURSQUARE_CLIENT_KEY = "4PQSM3203ZN13XY2GJCTH2ZBPU43KZGJXNJ4YOLDJ4OX4GDM";
    public static final String FOURSQUARE_CLIENT_SECRET = "VQP3TG3GKJPBHWYSASZJ1PCAZJFRBPGGW1VPEUXV0FJ2YYIX";
    public static final String MAPBOX_ACCESS_TOKEN = "";
}
